config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'main/index'
  get 'main/cabinet'
  post 'main/create', as: 'main_create'
  post 'create_history', to: 'main#create_history'
  
  #------------
  delete 'main/delete/:id', to: 'main#delete'
  put 'main/update/:id', to: 'main#update'
  #------------

  get 'registration', to: 'main#registration', as: "registration"

  root to: 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many :histories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :admin_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def registration
  	if current_admin_user
  		redirect_to admin_root
  	else
  		@admin_user = AdminUser.new
  	end
  end

  def create
  	@admin_user = AdminUser.create(admin_user_params)

  	if @admin_user.save
  		sign_in("admin_user", @admin_user)
  		redirect_to admin_root_url
  		#redirect_to admin_user_session_path(admin_user: { email: @admin_user.email, password: admin_user_params.params })
  	else 
  		@errors = @admin_user.errors
  		render :registration
  	end
  end

  def create_history
  	if current_admin_user
  		history = current_admin_user.histories.build(history_params)
  		if history.save
  			render :json => "successful".to_json
  		else
  			render :json => "failure".to_json
  		end
  	else
  		render nothing: true
  	end
  end

  def cabinet
  	
  end

  def history_params
  	params.require(:history).permit(:weight, :physical_activity, :capacity)
  end
  
  def update
    id, data = params[:id], params[:data]
    if current_admin_user
      history = current_admin_user.histories.find(id)
      history.update_attributes(data)
      redirect_to root_url
    end
  end
  
  def delete
    id = params[:id]
    if current_admin_user
      history = current_admin_user.histories.find(id)
      history.delete
      redirect_to root_url
    end
  end

  def admin_user_params
  	params.require(:admin_user).permit(:name, :email, :bort_at, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaterCalculator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="center">
	  	  <div class="top">
	  	  	<% if current_admin_user %>
	  	  		<%= link_to "Go to history", admin_histories_path %> | 
	  	  		<%= link_to "Logout", destroy_admin_user_session_path, data_method: :delete %>
		  	<% else %>
		  	  	<%= link_to "Login", new_admin_user_session_path %> |
		  	  	<%= link_to "Registration", registration_path %>
		  	<% end %>
	  	  </div>
	    <%= yield %>
	   </div>


    	<%= javascript_include_tag 'waterCalculator', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Рассчет употребления воды в день</h1>

<div class="content">
	<div class="params">
		<div class="gender">
			<h3>Пол</h3>
			<span class="selected-gender" data-param="man">Мужской</span>
			<span data-param="woman">Женский</span>
		</div>
		
		<h3 class="weight-label">Вес <span></span></h3>
		<div class="weight">
			<div class="slider"></div>
		</div>
		
		<h3 class="physical-label">Физическая активность <span></span></h3>
		<div class="physical-activity">
			<div class="slider"></div>
		</div>

		<div style="margin-top: 20px;">
			<p class="successful">Successful!</p>
			<p class="failed">Failed!</p>

			<% if current_admin_user %><button class="save">Save</button><% end %>
		</div>
	</div>

	<div class="result">
		<h2 class="total">Рекомендовано для потребления <br><span></span> в день</h2>
		<div class="b-bottle-cals">
			<i class="bottle-cals-patt"></i>
			<i class="bottle-cals-bg"></i>
		</div>
	</div>
</div>
</div>

app/views/main/registration.html.erb
<h1 style="margin-top: 10px;">Registration</h1>
<%= form_for(@admin_user, url: main_create_path) do |f| %>
	<% if @errors %>
	 	<% @errors.each do |k, v| %>
	 		<p><strong><%= k.capitalize %></strong> <%= v %></p>
	 	<% end %>
	<% end %>
	<div class="field">
		<%= f.label :email %> <br/>
		<%= f.email_field :email %> <br/>
	</div>

	<div class="field">
		<%= f.label :name %> <br/>
		<%= f.text_field :name %> <br/>
	</div>

	<div class="field">
		<%= f.label :bort_at %> <br/>
		<%= f.text_field :bort_at, class: 'born_at' %> <br/>
	</div>

	<div class="field">
		<%= f.label :password %> <br/>
		<%= f.password_field :password %> <br/>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>